//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Police2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public string AutoNumber { get; set; }
        public string Description { get; set; }
        public int IdStatus { get; set; }
        public int IdUser { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
